"""Rename model

Revision ID: b9bd0add8026
Revises: 13d07a35a20d
Create Date: 2023-05-10 23:57:55.432257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bd0add8026'
down_revision = '13d07a35a20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('donation','donations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('donations', 'donation')
    # ### end Alembic commands ###
